<?php
function brief_permission() {
  $permissions = array();
  $permissions['brief create'] = array(
    'title' => t('Create brief'),
  );
  $permissions['brief view'] = array(
    'title' => t('View brief'),
  );
  $permissions['brief edit'] = array(
    'title' => t('Edit brief'),
  );
  return $permissions;
}

function brief_theme() {
  $themes = array();
  $themes['brief_list'] = array(
    'template' => 'brief-list',
    'variables' => array('briefs' => array()),
  );
  $themes['brief'] = array(
    'template' => 'brief',
    'variables' => array(
      'company' => '',
      'finance' => '',
    ),
  );
  return $themes;
}

